//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        public string MaCauHoi { get; set; }
        public string MaDe { get; set; }
        public string CauHoi1 { get; set; }
        public string DapA { get; set; }
        public string DapB { get; set; }
        public string DapC { get; set; }
        public string DapD { get; set; }
        public string DapAn { get; set; }
    }
}
